#!/usr/bin/env python3
"""
Script para configurar RDS MySQL na AWS
"""

print('🗄️ CONFIGURANDO RDS MYSQL NA AWS')
print('=' * 60)

print('✅ EXCELENTE ESCOLHA!')
print('   RDS é muito mais profissional e confiável')
print('   - ✅ Backup automático')
print('   - ✅ Escalabilidade')
print('   - ✅ Alta disponibilidade')
print('   - ✅ Monitoramento')
print('   - ✅ SSL automático')
print()

print('🎯 PASSO 1: CRIAR RDS MYSQL')
print('=' * 50)
print('1. 🌐 Acessar AWS Console')
print('   https://console.aws.amazon.com')
print()
print('2. 🔍 Procurar por "RDS"')
print('   - Digite "RDS" na barra de pesquisa')
print('   - Clique em "RDS" (Relational Database Service)')
print()
print('3. ➕ Criar banco de dados')
print('   - Clique em "Create database"')
print('   - Escolha "MySQL"')
print('   - Template: "Free tier"')
print()
print('4. 📋 Configurar instância')
print('   - DB instance identifier: mercadolivre-db')
print('   - Master username: admin')
print('   - Master password: MercadoLivre2024! (senha forte)')
print('   - DB instance class: db.t2.micro (Free tier)')
print('   - Storage: 20 GB (Free tier)')
print()
print('5. 🔧 Configurações avançadas')
print('   - VPC: Default VPC')
print('   - Subnet group: Default')
print('   - Security group: Create new')
print('   - Port: 3306')
print()
print('6. 🚀 Criar banco')
print('   - Clique em "Create database"')
print('   - Aguarde criação (5-10 minutos)')
print()

print('🎯 PASSO 2: CONFIGURAR SECURITY GROUP')
print('=' * 50)
print('1. 🔍 Procurar por "EC2"')
print('   - Digite "EC2" na barra de pesquisa')
print('   - Clique em "EC2"')
print()
print('2. 📋 Ir em "Security Groups"')
print('   - Menu lateral > "Security Groups"')
print()
print('3. 🎯 Encontrar Security Group do RDS')
print('   - Procure por "mercadolivre-db" ou similar')
print('   - Clique no Security Group')
print()
print('4. ✏️ Editar "Inbound rules"')
print('   - Clique em "Edit inbound rules"')
print('   - Adicionar regra:')
print('     - Type: MySQL/Aurora')
print('     - Port: 3306')
print('     - Source: Custom')
print('     - IP: 0.0.0.0/0 (para permitir acesso da EC2)')
print('   - Clique em "Save rules"')
print()

print('🎯 PASSO 3: OBTER ENDPOINT')
print('=' * 50)
print('1. 🔍 Voltar para RDS')
print('   - Digite "RDS" na barra de pesquisa')
print('   - Clique em "RDS"')
print()
print('2. 📋 Ir em "Databases"')
print('   - Clique em "Databases"')
print()
print('3. 🎯 Clicar no banco criado')
print('   - Clique em "mercadolivre-db"')
print()
print('4. 📋 Copiar endpoint')
print('   - Copie o "Endpoint"')
print('   - Exemplo: mercadolivre-db.xxxxxxxxxxxx.sa-east-1.rds.amazonaws.com')
print()

print('🎯 PASSO 4: CONFIGURAR APLICAÇÃO')
print('=' * 50)
print('1. 📝 Editar arquivo .env na EC2')
print('   nano /home/ec2-user/mercadolivre-app/.env')
print()
print('2. 🔄 Atualizar configurações do banco')
print('   DB_HOST=mercadolivre-db.xxxxxxxxxxxx.sa-east-1.rds.amazonaws.com')
print('   DB_USER=admin')
print('   DB_PASSWORD=MercadoLivre2024!')
print('   DB_NAME=sistema_ml')
print('   DB_PORT=3306')
print('   DB_SSL_MODE=REQUIRED')
print()
print('3. 💾 Salvar arquivo')
print('   Ctrl+X, Y, Enter')
print()

print('🎯 PASSO 5: TESTAR CONEXÃO')
print('=' * 50)
print('1. 🔧 Instalar cliente MySQL na EC2')
print('   sudo yum install mysql -y')
print()
print('2. 🧪 Testar conexão')
print('   mysql -h mercadolivre-db.xxxxxxxxxxxx.sa-east-1.rds.amazonaws.com \\')
print('         -u admin -p')
print('   # Digite a senha: MercadoLivre2024!')
print()
print('3. 🗄️ Criar banco de dados')
print('   CREATE DATABASE sistema_ml;')
print('   USE sistema_ml;')
print('   SHOW TABLES;')
print('   EXIT;')
print()

print('🎯 PASSO 6: REINICIAR APLICAÇÃO')
print('=' * 50)
print('1. 🚀 Reiniciar serviços')
print('   sudo systemctl restart flask-app')
print('   sudo systemctl restart nginx')
print()
print('2. ✅ Verificar status')
print('   sudo systemctl status flask-app')
print('   sudo systemctl status nginx')
print()
print('3. 📋 Verificar logs')
print('   sudo journalctl -u flask-app -f')
print()

print('🎯 RESUMO DOS PASSOS:')
print('=' * 50)
print('1. 🏗️ Criar RDS MySQL (AWS Console)')
print('2. 🔧 Configurar Security Group')
print('3. 📋 Obter endpoint')
print('4. ⚙️ Configurar aplicação')
print('5. 🧪 Testar conexão')
print('6. 🚀 Reiniciar aplicação')
print()

print('💡 DICAS IMPORTANTES:')
print('=' * 50)
print('🔒 Segurança:')
print('   - Use senha forte')
print('   - Configure Security Group corretamente')
print('   - Use SSL (DB_SSL_MODE=REQUIRED)')
print()
print('⚡ Performance:')
print('   - RDS é muito mais rápido que MySQL local')
print('   - Backup automático')
print('   - Escalabilidade automática')
print()
print('💰 Custos:')
print('   - Free Tier: 750 horas/mês por 12 meses')
print('   - Depois: ~$15-20/mês')
print()

print('🎉 VANTAGENS DO RDS:')
print('=' * 50)
print('✅ Backup automático')
print('✅ Escalabilidade')
print('✅ Alta disponibilidade')
print('✅ Monitoramento')
print('✅ SSL automático')
print('✅ Manutenção automática')
print('✅ Performance otimizada')
print()

print('🚀 SUA APLICAÇÃO ESTARÁ PROFISSIONAL!')
print('RDS é a escolha certa para produção!')
