#!/usr/bin/env python3
"""
Script para configurar aplicação completa na instância EC2
"""

print('🚀 CONFIGURANDO APLICAÇÃO NA INSTÂNCIA EC2')
print('=' * 70)

print('📋 SUAS CREDENCIAIS:')
print('   MELI_APP_ID: 51467849418990')
print('   MELI_CLIENT_SECRET: KQGTjuxX0LfXVTw9MIVLYtykiTuWWniT')
print('   MELI_REDIRECT_URI: https://c1979facbdcd.ngrok-free.app/callback')
print('   DB_HOST: 127.0.0.1')
print('   DB_USER: root')
print('   DB_PASSWORD: 2154')
print('   DB_NAME: sistema_ml')
print()

print('🖥️ SUA INSTÂNCIA EC2:')
print('   IP Público: 56.124.88.188')
print('   DNS: ec2-56-124-88-188.sa-east-1.compute.amazonaws.com')
print('   Tipo: t3.micro')
print('   Região: sa-east-1 (São Paulo)')
print()

print('🔧 COMANDOS PARA EXECUTAR NA INSTÂNCIA:')
print()

print('1. 📱 CONECTAR VIA SSH:')
print('   ssh -i sua-chave.pem ec2-user@56.124.88.188')
print()

print('2. 🔄 ATUALIZAR SISTEMA:')
print('   sudo yum update -y')
print()

print('3. 🐍 INSTALAR PYTHON:')
print('   sudo yum install python3.11 python3.11-pip -y')
print('   sudo yum install git -y')
print()

print('4. 📁 CRIAR DIRETÓRIO:')
print('   mkdir -p /home/ec2-user/mercadolivre-app')
print('   cd /home/ec2-user/mercadolivre-app')
print()

print('5. 📤 UPLOAD DOS ARQUIVOS:')
print('   # Opção 1: Usar scp do seu computador')
print('   scp -i sua-chave.pem -r . ec2-user@56.124.88.188:/home/ec2-user/mercadolivre-app/')
print('   ')
print('   # Opção 2: Usar git (se tiver repositório)')
print('   git clone https://github.com/seu-usuario/seu-repo.git .')
print()

print('6. 🔧 CONFIGURAR .ENV:')
print('   nano .env')
print()

print('   # Conteúdo do arquivo .env:')
print('   FLASK_ENV=production')
print('   DEBUG=False')
print('   FLASK_SECRET_KEY=sua_chave_secreta_muito_forte_aqui')
print('   ')
print('   # Banco de dados')
print('   DB_HOST=127.0.0.1')
print('   DB_USER=root')
print('   DB_PASSWORD=2154')
print('   DB_NAME=sistema_ml')
print('   DB_PORT=3306')
print('   ')
print('   # Mercado Livre')
print('   MELI_APP_ID=51467849418990')
print('   MELI_CLIENT_SECRET=KQGTjuxX0LfXVTw9MIVLYtykiTuWWniT')
print('   MELI_REDIRECT_URI=http://56.124.88.188/callback')
print()

print('7. 📦 INSTALAR DEPENDÊNCIAS:')
print('   pip3.11 install Flask mysql-connector-python python-dotenv requests httpx pandas openpyxl reportlab')
print()

print('8. 🗄️ INSTALAR MYSQL:')
print('   sudo yum install mysql-server -y')
print('   sudo systemctl start mysqld')
print('   sudo systemctl enable mysqld')
print('   sudo mysql_secure_installation')
print()

print('9. 🔧 CONFIGURAR MYSQL:')
print('   sudo mysql -u root -p')
print('   ')
print('   # No MySQL:')
print('   CREATE DATABASE sistema_ml;')
print('   CREATE USER "admin"@"%" IDENTIFIED BY "2154";')
print('   GRANT ALL PRIVILEGES ON sistema_ml.* TO "admin"@"%";')
print('   FLUSH PRIVILEGES;')
print('   EXIT;')
print()

print('10. 🌐 CONFIGURAR NGINX:')
print('    sudo yum install nginx -y')
print('    sudo nano /etc/nginx/conf.d/flask.conf')
print()
print('    # Conteúdo do arquivo:')
print('    server {')
print('        listen 80;')
print('        server_name 56.124.88.188;')
print('        ')
print('        location / {')
print('            proxy_pass http://127.0.0.1:5000;')
print('            proxy_set_header Host $host;')
print('            proxy_set_header X-Real-IP $remote_addr;')
print('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;')
print('            proxy_set_header X-Forwarded-Proto $scheme;')
print('        }')
print('    }')
print()

print('11. 🔧 CONFIGURAR SERVIÇO:')
print('    sudo nano /etc/systemd/system/flask-app.service')
print()
print('    # Conteúdo do arquivo:')
print('    [Unit]')
print('    Description=Flask App')
print('    After=network.target')
print('    ')
print('    [Service]')
print('    User=ec2-user')
print('    WorkingDirectory=/home/ec2-user/mercadolivre-app')
print('    Environment=PATH=/usr/bin/python3.11')
print('    ExecStart=/usr/bin/python3.11 app.py')
print('    Restart=always')
print('    ')
print('    [Install]')
print('    WantedBy=multi-user.target')
print()

print('12. 🚀 INICIAR SERVIÇOS:')
print('    sudo systemctl daemon-reload')
print('    sudo systemctl start nginx')
print('    sudo systemctl enable nginx')
print('    sudo systemctl start flask-app')
print('    sudo systemctl enable flask-app')
print()

print('13. 🔥 CONFIGURAR FIREWALL:')
print('    sudo firewall-cmd --permanent --add-port=80/tcp')
print('    sudo firewall-cmd --permanent --add-port=443/tcp')
print('    sudo firewall-cmd --reload')
print()

print('14. ✅ VERIFICAR STATUS:')
print('    sudo systemctl status nginx')
print('    sudo systemctl status flask-app')
print('    sudo systemctl status mysqld')
print()

print('15. 🌐 TESTAR APLICAÇÃO:')
print('    # Acessar no navegador:')
print('    http://56.124.88.188')
print()

print('⚠️ IMPORTANTE - SECURITY GROUPS:')
print('   Certifique-se de que sua instância EC2 tem as portas abertas:')
print('   1. AWS Console > EC2 > Security Groups')
print('   2. Encontrar o security group da sua instância')
print('   3. Editar "Inbound rules"')
print('   4. Adicionar regras:')
print('      - Type: SSH, Port: 22, Source: 0.0.0.0/0')
print('      - Type: HTTP, Port: 80, Source: 0.0.0.0/0')
print('      - Type: HTTPS, Port: 443, Source: 0.0.0.0/0')
print()

print('🎯 RESUMO DOS PASSOS:')
print('   1. Conectar via SSH')
print('   2. Instalar Python e dependências')
print('   3. Upload dos arquivos da aplicação')
print('   4. Configurar .env com suas credenciais')
print('   5. Instalar e configurar MySQL')
print('   6. Configurar Nginx')
print('   7. Configurar serviço systemd')
print('   8. Iniciar serviços')
print('   9. Configurar firewall')
print('   10. Testar aplicação')
print()

print('⏱️ TEMPO ESTIMADO: 30-45 minutos')
print('🎉 RESULTADO: Aplicação rodando em http://56.124.88.188')
