#!/usr/bin/env python3
"""
Script para configurar AWS RDS MySQL gratuito
"""

print('🚀 CONFIGURANDO AWS RDS MYSQL GRATUITO')
print('=' * 60)

print('✅ VANTAGENS DO AWS RDS:')
print('   - 750 horas/mês por 12 meses')
print('   - 20GB storage gratuito')
print('   - MySQL nativo (zero adaptações)')
print('   - SSL automático')
print('   - Backup automático')
print('   - Escalável')
print('   - Managed pela AWS')
print()

print('📋 PASSOS PARA CONFIGURAR:')
print()

print('1. 🏗️ CRIAR CONTA AWS:')
print('   - Acessar https://aws.amazon.com')
print('   - Clicar em "Create an AWS Account"')
print('   - Preencher dados pessoais')
print('   - Verificar telefone')
print('   - Escolher "Basic Support - Free"')
print()

print('2. 🗄️ CRIAR RDS MYSQL:')
print('   - Acessar AWS Console')
print('   - Ir em "RDS" (Relational Database Service)')
print('   - Clicar em "Create database"')
print('   - Escolher "MySQL"')
print('   - Template: "Free tier"')
print('   - DB instance identifier: "mercadolivre-db"')
print('   - Master username: "admin"')
print('   - Master password: escolher senha forte')
print('   - Clicar em "Create database"')
print()

print('3. 🔒 CONFIGURAR SEGURANÇA:')
print('   - Ir em "Security Groups"')
print('   - Editar "Inbound rules"')
print('   - Adicionar regra:')
print('     * Type: MySQL/Aurora')
print('     * Port: 3306')
print('     * Source: 0.0.0.0/0 (para Vercel)')
print('   - Salvar regras')
print()

print('4. 📍 OBTER ENDPOINT:')
print('   - Ir em "Databases"')
print('   - Clicar no banco criado')
print('   - Copiar "Endpoint"')
print('   - Usar no Vercel')
print()

print('5. ⚙️ CONFIGURAR VERCEL:')
print('   DB_HOST=mercadolivre-db.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com')
print('   DB_USER=admin')
print('   DB_PASSWORD=sua_senha')
print('   DB_NAME=mercadolivre_lucratividade')
print('   DB_PORT=3306')
print('   DB_SSL_MODE=REQUIRED')
print()

print('⚠️ LIMITAÇÕES:')
print('   - 12 meses de uso gratuito')
print('   - Depois vira pago (~$15-20/mês)')
print('   - Limite de recursos (suficiente para começar)')
print()

print('🎯 RECOMENDAÇÃO:')
print('   AWS RDS é a melhor opção gratuita!')
print('   Zero adaptações no código.')
print()

print('🚀 PRÓXIMOS PASSOS:')
print('   1. Criar conta AWS')
print('   2. Criar RDS MySQL')
print('   3. Configurar segurança')
print('   4. Obter endpoint')
print('   5. Configurar no Vercel')
print('   6. Deploy da aplicação')
print()

print('⏱️ TEMPO ESTIMADO: 26 minutos')
print('🎉 RESULTADO: Aplicação online com banco MySQL gratuito!')
