#!/usr/bin/env python3
"""
Script para configurar Security Group do RDS com IP do EC2
"""

print('🔒 CONFIGURANDO SECURITY GROUP DO RDS')
print('=' * 50)

# IP privado do EC2
EC2_PRIVATE_IP = "172.31.2.15"

print(f'🎯 IP PRIVADO DO EC2: {EC2_PRIVATE_IP}')
print()

print('✅ CONFIGURAÇÃO DO SECURITY GROUP:')
print('=' * 50)
print('📋 REGRA PARA ADICIONAR:')
print('   Type: MySQL/Aurora')
print('   Protocol: TCP')
print('   Port: 3306')
print(f'   Source: {EC2_PRIVATE_IP}/32')
print()

print('🔧 PASSOS NO AWS CONSOLE:')
print('=' * 40)
print('1. 🌐 Acessar: https://console.aws.amazon.com')
print('2. 🔍 Navegar: Services → RDS → Databases')
print('3. 📋 Selecionar: mercadolivre-db')
print('4. 🔒 Ir para: Connectivity & security → VPC security groups')
print('5. ⚙️ Editar: Actions → Edit inbound rules')
print('6. ➕ Adicionar regra:')
print('   - Type: MySQL/Aurora')
print('   - Protocol: TCP')
print('   - Port: 3306')
print(f'   - Source: {EC2_PRIVATE_IP}/32')
print('7. 💾 Salvar: Save rules')
print()

print('🎯 CONFIGURAÇÃO EXATA:')
print('=' * 30)
print('📋 Inbound Rules:')
print('   Rule 1:')
print('   - Type: MySQL/Aurora')
print('   - Protocol: TCP')
print('   - Port: 3306')
print(f'   - Source: {EC2_PRIVATE_IP}/32')
print('   - Description: Allow EC2 access to RDS')
print()

print('⏱️ TEMPO DE PROPAGAÇÃO:')
print('=' * 30)
print('⏰ Security Group: 1-2 minutos')
print('⏰ Total: 2-3 minutos')
print()

print('🧪 APÓS CONFIGURAR:')
print('=' * 30)
print('1. ⏳ Aguardar 2-3 minutos')
print('2. 🧪 Testar conexão:')
print('   python3.11 test_rds_connection.py')
print('3. 🗄️ Criar banco:')
print('   python3.11 create_database.py')
print()

print('🔍 VERIFICAR SE FUNCIONOU:')
print('=' * 40)
print('✅ Se a conexão funcionar:')
print('   - RDS conectado')
print('   - Banco criado')
print('   - Aplicação configurada')
print()
print('❌ Se ainda der erro:')
print('   - Verificar se regra foi salva')
print('   - Aguardar mais tempo')
print('   - Verificar IP correto')
print()

print('🚨 IMPORTANTE:')
print('=' * 20)
print(f'✅ IP do EC2: {EC2_PRIVATE_IP}')
print('✅ Formato: IP/32')
print(f'✅ Regra: {EC2_PRIVATE_IP}/32')
print('✅ Aguarde 2-3 minutos')
print()

print('🚀 CONFIGURE O SECURITY GROUP E TESTE!')
print('=' * 50)
print('1. 🔒 Configurar Security Group')
print('2. ⏳ Aguardar 2-3 minutos')
print('3. 🧪 Testar conexão')
print('4. 🗄️ Criar banco')
print('5. ⚙️ Configurar aplicação')
print('6. 🚀 Reiniciar aplicação')
print('7. 🌐 Testar aplicação online')
