#!/usr/bin/env python3
"""
Script para corrigir configuração de firewall no Amazon Linux 2023
"""

print('🔥 CORRIGINDO FIREWALL NO AMAZON LINUX 2023')
print('=' * 60)

print('❌ PROBLEMA IDENTIFICADO:')
print('   firewall-cmd: command not found')
print()
print('💡 EXPLICAÇÃO:')
print('   O Amazon Linux 2023 usa "iptables" em vez de "firewalld"')
print('   Por isso o comando firewall-cmd não funciona')
print()

print('✅ SOLUÇÃO: USAR IPTABLES')
print('=' * 40)
print('1. 🔧 Instalar iptables (se necessário):')
print('   sudo yum install iptables-services -y')
print()
print('2. 🔥 Configurar regras de firewall:')
print('   sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT')
print('   sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT')
print('   sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT')
print('   sudo iptables -A INPUT -j DROP')
print()
print('3. 💾 Salvar regras:')
print('   sudo service iptables save')
print()
print('4. 🚀 Habilitar iptables:')
print('   sudo systemctl enable iptables')
print('   sudo systemctl start iptables')
print()

print('🎯 COMANDOS COMPLETOS PARA EXECUTAR:')
print('=' * 50)
print('# Instalar iptables')
print('sudo yum install iptables-services -y')
print()
print('# Configurar regras')
print('sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT')
print('sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT')
print('sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT')
print('sudo iptables -A INPUT -j DROP')
print()
print('# Salvar e habilitar')
print('sudo service iptables save')
print('sudo systemctl enable iptables')
print('sudo systemctl start iptables')
print()

print('🔍 VERIFICAR CONFIGURAÇÃO:')
print('=' * 40)
print('1. 📋 Ver regras ativas:')
print('   sudo iptables -L')
print()
print('2. ✅ Verificar status:')
print('   sudo systemctl status iptables')
print()
print('3. 🌐 Testar conectividade:')
print('   curl -I http://localhost')
print('   curl -I http://SEU_IP_PUBLICO')
print()

print('🚨 ALTERNATIVA: USAR SECURITY GROUPS')
print('=' * 50)
print('💡 DICA: O mais fácil é configurar no AWS Console:')
print()
print('1. 🌐 Acessar AWS Console')
print('2. 🔍 Procurar por "EC2"')
print('3. 📋 Ir em "Security Groups"')
print('4. 🎯 Encontrar o Security Group da sua instância')
print('5. ✏️ Editar "Inbound rules"')
print('6. ➕ Adicionar regras:')
print('   - Type: SSH, Port: 22, Source: My IP')
print('   - Type: HTTP, Port: 80, Source: 0.0.0.0/0')
print('   - Type: HTTPS, Port: 443, Source: 0.0.0.0/0')
print('7. 💾 Salvar regras')
print()

print('🎯 RESUMO:')
print('=' * 30)
print('✅ Problema: firewall-cmd não existe no Amazon Linux 2023')
print('✅ Solução 1: Usar iptables (comandos acima)')
print('✅ Solução 2: Configurar Security Groups no AWS Console')
print('✅ Recomendação: Usar Security Groups (mais fácil)')
print()

print('🚀 PRÓXIMOS PASSOS:')
print('=' * 30)
print('1. 🔧 Configurar firewall (iptables ou Security Groups)')
print('2. ✅ Verificar status dos serviços')
print('3. 🌐 Testar aplicação no navegador')
print('4. 📋 Verificar logs se necessário')
print()

print('🎉 SUA APLICAÇÃO ESTÁ QUASE PRONTA!')
print('Só falta configurar o firewall e testar!')
