#!/usr/bin/env python3
"""
Script para corrigir Security Group do RDS
"""

print('🔒 CORRIGINDO SECURITY GROUP DO RDS')
print('=' * 50)

print('❌ PROBLEMA IDENTIFICADO:')
print('   Porta 3306 não está acessível')
print('   Security Group bloqueando conexão')
print()

print('✅ SOLUÇÃO: CONFIGURAR SECURITY GROUP')
print('=' * 50)
print('🔧 PASSOS NO AWS CONSOLE:')
print()
print('1. 🌐 Acessar AWS Console')
print('   https://console.aws.amazon.com')
print()
print('2. 🔍 Navegar para RDS')
print('   Services → RDS → Databases')
print()
print('3. 📋 Selecionar seu banco')
print('   mercadolivre-db')
print()
print('4. 🔒 Ir para Security Groups')
print('   Database → Connectivity & security → VPC security groups')
print()
print('5. ⚙️ Editar Security Group')
print('   Clique no Security Group')
print('   Actions → Edit inbound rules')
print()
print('6. ➕ Adicionar regra')
print('   Type: MySQL/Aurora')
print('   Protocol: TCP')
print('   Port: 3306')
print('   Source: Custom')
print('   IP: 0.0.0.0/0 (ou IP do EC2: 172.31.4.248/32)')
print()
print('7. 💾 Salvar regra')
print('   Save rules')
print()

print('🎯 CONFIGURAÇÃO RECOMENDADA:')
print('=' * 40)
print('📋 REGRA 1 (Mais Segura):')
print('   Type: MySQL/Aurora')
print('   Protocol: TCP')
print('   Port: 3306')
print('   Source: 172.31.4.248/32 (IP do EC2)')
print()
print('📋 REGRA 2 (Menos Segura):')
print('   Type: MySQL/Aurora')
print('   Protocol: TCP')
print('   Port: 3306')
print('   Source: 0.0.0.0/0 (Qualquer IP)')
print()

print('🚨 IMPORTANTE:')
print('=' * 20)
print('⚠️ Regra 1 é mais segura (apenas EC2)')
print('⚠️ Regra 2 permite acesso de qualquer lugar')
print('✅ Recomendação: Use Regra 1')
print()

print('🔍 VERIFICAR IP DO EC2:')
print('=' * 30)
print('No EC2, execute:')
print('   curl -s http://169.254.169.254/latest/meta-data/public-ipv4')
print('   curl -s http://169.254.169.254/latest/meta-data/local-ipv4')
print()

print('⏱️ TEMPO DE PROPAGAÇÃO:')
print('=' * 30)
print('⏰ Security Group: 1-2 minutos')
print('⏰ DNS: 1-5 minutos')
print('⏰ Total: 2-7 minutos')
print()

print('🧪 APÓS CONFIGURAR:')
print('=' * 30)
print('1. ⏳ Aguardar 2-3 minutos')
print('2. 🧪 Testar conexão:')
print('   python3.11 test_rds_connection.py')
print('3. 🗄️ Criar banco:')
print('   python3.11 create_database.py')
print()

print('🎯 RESUMO:')
print('=' * 20)
print('✅ Problema: Security Group')
print('✅ Solução: Configurar regra')
print('✅ Porta: 3306')
print('✅ Fonte: IP do EC2')
print()
print('🚀 CONFIGURE O SECURITY GROUP E TESTE NOVAMENTE!')
