#!/usr/bin/env python3
"""
Script para corrigir instalação do MySQL no Amazon Linux 2023
"""

print('🗄️ CORRIGINDO INSTALAÇÃO MYSQL NO AMAZON LINUX 2023')
print('=' * 60)

print('❌ PROBLEMA IDENTIFICADO:')
print('   No match for argument: mysql-server')
print()
print('💡 EXPLICAÇÃO:')
print('   No Amazon Linux 2023, o MySQL tem nome diferente')
print('   Precisa usar "mysql" em vez de "mysql-server"')
print()

print('✅ SOLUÇÃO: INSTALAR MYSQL CORRETO')
print('=' * 50)
print('🔧 COMANDOS CORRETOS:')
print()
print('1. 📦 Instalar MySQL:')
print('   sudo yum install mysql -y')
print()
print('2. 🚀 Iniciar MySQL:')
print('   sudo systemctl start mysqld')
print('   sudo systemctl enable mysqld')
print()
print('3. 🔧 Configurar MySQL:')
print('   sudo mysql_secure_installation')
print('   # Responda: Y, Y, N, Y, Y')
print()
print('4. 🗄️ Criar banco de dados:')
print('   sudo mysql -u root -p')
print('   # No MySQL:')
print('   CREATE DATABASE sistema_ml;')
print('   CREATE USER "admin"@"%" IDENTIFIED BY "2154";')
print('   GRANT ALL PRIVILEGES ON sistema_ml.* TO "admin"@"%";')
print('   FLUSH PRIVILEGES;')
print('   EXIT;')
print()

print('🎯 COMANDOS COMPLETOS PARA EXECUTAR:')
print('=' * 50)
print('# 1. Instalar MySQL (nome correto)')
print('sudo yum install mysql -y')
print()
print('# 2. Iniciar MySQL')
print('sudo systemctl start mysqld')
print('sudo systemctl enable mysqld')
print()
print('# 3. Configurar MySQL')
print('sudo mysql_secure_installation')
print()
print('# 4. Criar banco de dados')
print('sudo mysql -u root -p')
print('# Executar comandos SQL acima')
print()
print('# 5. Verificar status')
print('sudo systemctl status mysqld')
print()
print('# 6. Reiniciar aplicação')
print('sudo systemctl restart flask-app')
print()

print('🔍 VERIFICAR INSTALAÇÃO:')
print('=' * 40)
print('📋 Verificar se MySQL está instalado:')
print('   mysql --version')
print()
print('📋 Verificar status do serviço:')
print('   sudo systemctl status mysqld')
print()
print('📋 Verificar se está rodando:')
print('   sudo systemctl is-active mysqld')
print()
print('📋 Verificar se está habilitado:')
print('   sudo systemctl is-enabled mysqld')
print()

print('🚨 ALTERNATIVA: USAR MARIADB')
print('=' * 50)
print('💡 DICA: Se MySQL não funcionar, use MariaDB:')
print()
print('1. 📦 Instalar MariaDB:')
print('   sudo yum install mariadb-server -y')
print()
print('2. 🚀 Iniciar MariaDB:')
print('   sudo systemctl start mariadb')
print('   sudo systemctl enable mariadb')
print()
print('3. 🔧 Configurar MariaDB:')
print('   sudo mysql_secure_installation')
print()
print('4. 🗄️ Criar banco de dados:')
print('   sudo mysql -u root -p')
print('   # Comandos SQL são os mesmos')
print()

print('🎯 RESUMO:')
print('=' * 30)
print('✅ Problema: mysql-server não existe no Amazon Linux 2023')
print('✅ Solução 1: Usar "mysql" em vez de "mysql-server"')
print('✅ Solução 2: Usar MariaDB como alternativa')
print('✅ Recomendação: Tentar MySQL primeiro, depois MariaDB')
print()

print('🚀 PRÓXIMOS PASSOS:')
print('=' * 30)
print('1. 🔧 Instalar MySQL com nome correto')
print('2. 🗄️ Configurar banco de dados')
print('3. 🚀 Reiniciar aplicação')
print('4. ✅ Verificar status')
print('5. 🌐 Testar aplicação')
print()

print('🎉 APÓS CORRIGIR:')
print('=' * 30)
print('✅ MySQL: active (running)')
print('✅ Flask-app: active (running)')
print('✅ Nginx: active (running)')
print('✅ Aplicação: http://SEU_IP_PUBLICO')
print()

print('🚀 SUA APLICAÇÃO ESTARÁ FUNCIONANDO!')
print('Só precisa instalar o MySQL com o nome correto!')
