#!/usr/bin/env python3
"""
Script para corrigir problemas identificados na EC2
"""

print('🔧 CORRIGINDO PROBLEMAS IDENTIFICADOS NA EC2')
print('=' * 60)

print('❌ PROBLEMAS IDENTIFICADOS:')
print('   1. IndentationError no app.py (linha 380-381)')
print('   2. MySQL não está instalado (mysqld.service not found)')
print()

print('✅ SOLUÇÃO 1: CORRIGIR ERRO DE INDENTAÇÃO')
print('=' * 50)
print('🔍 PROBLEMA:')
print('   IndentationError: expected an indented block after \'if\' statement on line 380')
print()
print('🔧 SOLUÇÃO:')
print('   1. 📝 Editar o arquivo app.py:')
print('      nano /home/ec2-user/mercadolivre-app/app.py')
print()
print('   2. 🔍 Ir para a linha 380-381')
print('   3. ✏️ Corrigir a indentação:')
print('      # Linha 380: if result[\'sucesso\']:')
print('      # Linha 381:     import_status[\'vendas\'][\'sucesso\'] += 1')
print('      # (Adicionar 4 espaços antes da linha 381)')
print()
print('   4. 💾 Salvar: Ctrl+X, Y, Enter')
print()

print('✅ SOLUÇÃO 2: INSTALAR MYSQL')
print('=' * 50)
print('🔍 PROBLEMA:')
print('   Unit mysqld.service could not be found')
print()
print('🔧 SOLUÇÃO:')
print('   1. 📦 Instalar MySQL:')
print('      sudo yum install mysql-server -y')
print()
print('   2. 🚀 Iniciar MySQL:')
print('      sudo systemctl start mysqld')
print('      sudo systemctl enable mysqld')
print()
print('   3. 🔧 Configurar MySQL:')
print('      sudo mysql_secure_installation')
print('      # Responda: Y, Y, N, Y, Y')
print()
print('   4. 🗄️ Criar banco de dados:')
print('      sudo mysql -u root -p')
print('      # No MySQL:')
print('      CREATE DATABASE sistema_ml;')
print('      CREATE USER "admin"@"%" IDENTIFIED BY "2154";')
print('      GRANT ALL PRIVILEGES ON sistema_ml.* TO "admin"@"%";')
print('      FLUSH PRIVILEGES;')
print('      EXIT;')
print()

print('🎯 COMANDOS COMPLETOS PARA EXECUTAR:')
print('=' * 50)
print('# 1. Corrigir indentação no app.py')
print('nano /home/ec2-user/mercadolivre-app/app.py')
print('# Ir para linha 380-381 e corrigir indentação')
print()
print('# 2. Instalar MySQL')
print('sudo yum install mysql-server -y')
print('sudo systemctl start mysqld')
print('sudo systemctl enable mysqld')
print('sudo mysql_secure_installation')
print()
print('# 3. Criar banco de dados')
print('sudo mysql -u root -p')
print('# Executar comandos SQL acima')
print()
print('# 4. Reiniciar serviços')
print('sudo systemctl restart flask-app')
print('sudo systemctl restart nginx')
print()
print('# 5. Verificar status')
print('sudo systemctl status nginx')
print('sudo systemctl status flask-app')
print('sudo systemctl status mysqld')
print()

print('🔍 VERIFICAR LOGS:')
print('=' * 30)
print('📋 Ver logs da aplicação:')
print('   sudo journalctl -u flask-app -f')
print()
print('📋 Ver logs do MySQL:')
print('   sudo journalctl -u mysqld -f')
print()
print('📋 Ver logs do Nginx:')
print('   sudo journalctl -u nginx -f')
print()

print('🚨 SOLUÇÃO DE PROBLEMAS:')
print('=' * 40)
print('❌ Se ainda houver erro de indentação:')
print('   1. Verificar se todas as linhas estão corretas')
print('   2. Usar espaços em vez de tabs')
print('   3. Verificar se não há caracteres especiais')
print()
print('❌ Se MySQL não conectar:')
print('   1. Verificar se MySQL está rodando')
print('   2. Verificar se o banco existe')
print('   3. Verificar se o usuário tem permissões')
print()
print('❌ Se a aplicação não carregar:')
print('   1. Verificar logs da aplicação')
print('   2. Verificar se todas as dependências estão instaladas')
print('   3. Verificar se o arquivo .env está correto')
print()

print('🎯 RESUMO DOS PASSOS:')
print('=' * 30)
print('1. 🔧 Corrigir indentação no app.py')
print('2. 📦 Instalar MySQL')
print('3. 🗄️ Configurar banco de dados')
print('4. 🚀 Reiniciar serviços')
print('5. ✅ Verificar status')
print('6. 🌐 Testar aplicação')
print()

print('🎉 APÓS CORRIGIR:')
print('=' * 30)
print('✅ Nginx: active (running)')
print('✅ Flask-app: active (running)')
print('✅ MySQL: active (running)')
print('✅ Aplicação: http://SEU_IP_PUBLICO')
print()

print('🚀 SUA APLICAÇÃO ESTARÁ FUNCIONANDO!')
print('Só precisa corrigir esses dois problemas!')
