#!/usr/bin/env python3
"""
Guia visual para usar WinSCP
"""

print('📁 GUIA VISUAL WINSCP - PASSO A PASSO')
print('=' * 60)

print('🎯 OBJETIVO: Fazer upload dos arquivos da aplicação para AWS')
print()

print('📥 PASSO 1: BAIXAR E INSTALAR WINSCP')
print('=' * 40)
print('1. 🌐 Acessar: https://winscp.net/')
print('2. 📥 Baixar: "Download WinSCP"')
print('3. 🔧 Instalar: Executar o instalador')
print('4. ✅ Escolher: "Typical installation"')
print('5. 🎉 Finalizar: "Finish"')
print()

print('🔧 PASSO 2: CONFIGURAR CONEXÃO')
print('=' * 40)
print('1. 🚀 Abrir WinSCP')
print('2. ➕ Clicar: "New Session" (Ctrl+N)')
print('3. 📋 Preencher:')
print('   - File protocol: SFTP')
print('   - Host name: SEU_IP_PUBLICO_DA_EC2')
print('   - Port number: 22')
print('   - User name: ec2-user')
print('   - Password: (deixar vazio)')
print('4. ⚙️ Configurar chave SSH:')
print('   - Clicar: "Advanced..."')
print('   - Ir em: SSH > Authentication')
print('   - Clicar: "..." ao lado de "Private key file"')
print('   - Selecionar: Seu arquivo .pem')
print('5. 💾 Salvar: "Save..." > "MercadoLivre AWS"')
print()

print('🔌 PASSO 3: CONECTAR À EC2')
print('=' * 40)
print('1. 🎯 Selecionar: "MercadoLivre AWS"')
print('2. 🔗 Clicar: "Login"')
print('3. ⚠️ Aceitar: "Yes" (primeira vez)')
print('4. ✅ Marcar: "Add host key to cache"')
print()

print('📁 PASSO 4: ENTENDER A INTERFACE')
print('=' * 40)
print('┌─────────────────────────────────────────────────────────────┐')
print('│  WinSCP - MercadoLivre AWS                                 │')
print('├─────────────────┬───────────────────────────────────────────┤')
print('│  Local (Seu PC) │  Remote (Servidor AWS)                   │')
print('│                 │                                           │')
print('│  📁 Desktop     │  📁 /home/ec2-user                       │')
print('│  📁 Documents   │  📁 /home/ec2-user/mercadolivre-app     │')
print('│  📁 Downloads   │  📁 /var/log                             │')
print('│  📁 ...         │  📁 /etc                                 │')
print('└─────────────────┴───────────────────────────────────────────┘')
print()

print('📤 PASSO 5: FAZER UPLOAD')
print('=' * 40)
print('1. 🖱️ Selecionar: mercadolivre_app_ec2.zip (lado esquerdo)')
print('2. 🚀 Arrastar: Do lado esquerdo para o direito')
print('3. 📋 Confirmar: "OK"')
print('4. ⏳ Aguardar: Upload terminar')
print('5. ✅ Verificar: Arquivo aparece no servidor')
print()

print('🎯 LOCALIZAÇÃO DOS ARQUIVOS')
print('=' * 40)
print('📁 Seu PC (lado esquerdo):')
print('   - Navegue até onde salvou mercadolivre_app_ec2.zip')
print('   - Geralmente em: Downloads ou Desktop')
print()
print('📁 Servidor AWS (lado direito):')
print('   - Navegue até: /home/ec2-user/mercadolivre-app')
print('   - Clique duas vezes nas pastas para entrar')
print()

print('🔧 COMANDOS ÚTEIS')
print('=' * 40)
print('📁 Criar pasta:')
print('   - Botão direito > New > Directory')
print()
print('✏️ Renomear:')
print('   - Botão direito > Rename')
print()
print('🗑️ Excluir:')
print('   - Botão direito > Delete')
print()
print('📝 Editar:')
print('   - Duplo clique no arquivo')
print()

print('🚨 SOLUÇÃO DE PROBLEMAS')
print('=' * 40)
print('❌ "Connection refused":')
print('   - Verificar se EC2 está rodando')
print('   - Verificar Security Group (porta 22)')
print('   - Verificar IP público')
print()
print('❌ "Authentication failed":')
print('   - Verificar arquivo .pem')
print('   - Verificar usuário "ec2-user"')
print('   - Verificar configuração da chave SSH')
print()
print('❌ "Permission denied":')
print('   - Navegar para /home/ec2-user/')
print('   - Verificar se pasta existe')
print('   - Verificar permissões')
print()

print('📋 CHECKLIST DE UPLOAD')
print('=' * 40)
print('✅ Antes de conectar:')
print('   - WinSCP instalado')
print('   - Arquivo .pem da chave SSH')
print('   - IP público da instância EC2')
print('   - Arquivo mercadolivre_app_ec2.zip')
print()
print('✅ Durante a conexão:')
print('   - Protocolo SFTP')
print('   - Host name correto')
print('   - Usuário "ec2-user"')
print('   - Chave SSH configurada')
print()
print('✅ Após o upload:')
print('   - Arquivo enviado com sucesso')
print('   - Arquivo aparece no servidor')
print('   - Conexão estável')
print('   - Pronto para próximos passos')
print()

print('💡 DICAS IMPORTANTES')
print('=' * 40)
print('🔒 Segurança:')
print('   - Nunca compartilhe sua chave SSH')
print('   - Sempre desconecte após usar')
print('   - Mantenha o WinSCP atualizado')
print()
print('⚡ Performance:')
print('   - Feche outros programas durante upload')
print('   - Use conexão estável (cabo ethernet)')
print('   - Evite uploads simultâneos')
print()
print('📁 Organização:')
print('   - Mantenha arquivos organizados')
print('   - Use nomes descritivos')
print('   - Faça backup dos arquivos importantes')
print()

print('🎯 PRÓXIMOS PASSOS')
print('=' * 40)
print('Após fazer upload do arquivo ZIP:')
print('1. 🔗 Conectar via SSH para extrair arquivos')
print('2. 📦 Instalar dependências Python')
print('3. ⚙️ Configurar serviços (Nginx, systemd)')
print('4. 🌐 Testar aplicação no navegador')
print()

print('🎉 RESUMO')
print('=' * 40)
print('✅ O que você aprendeu:')
print('   - Instalar WinSCP')
print('   - Configurar conexão com AWS')
print('   - Navegar pelos arquivos')
print('   - Fazer upload de arquivos')
print('   - Resolver problemas comuns')
print()
print('🚀 Agora você pode:')
print('   - Conectar à sua instância EC2')
print('   - Transferir arquivos facilmente')
print('   - Gerenciar arquivos no servidor')
print('   - Configurar sua aplicação')
print()
print('🎯 Pronto para fazer upload da sua aplicação!')
