#!/usr/bin/env python3
"""
Script para instalar MariaDB no Amazon Linux 2023
"""

print('🗄️ INSTALANDO MARIADB NO AMAZON LINUX 2023')
print('=' * 60)

print('❌ PROBLEMA IDENTIFICADO:')
print('   No match for argument: mysql')
print()
print('💡 EXPLICAÇÃO:')
print('   No Amazon Linux 2023, nem MySQL nem MariaDB estão nos repositórios padrão')
print('   Precisa habilitar repositórios extras ou usar MariaDB')
print()

print('✅ SOLUÇÃO: INSTALAR MARIADB')
print('=' * 50)
print('🔧 COMANDOS CORRETOS:')
print()
print('1. 📦 Instalar MariaDB:')
print('   sudo yum install mariadb-server -y')
print()
print('2. 🚀 Iniciar MariaDB:')
print('   sudo systemctl start mariadb')
print('   sudo systemctl enable mariadb')
print()
print('3. 🔧 Configurar MariaDB:')
print('   sudo mysql_secure_installation')
print('   # Responda: Y, Y, N, Y, Y')
print()
print('4. 🗄️ Criar banco de dados:')
print('   sudo mysql -u root -p')
print('   # No MySQL/MariaDB:')
print('   CREATE DATABASE sistema_ml;')
print('   CREATE USER "admin"@"%" IDENTIFIED BY "2154";')
print('   GRANT ALL PRIVILEGES ON sistema_ml.* TO "admin"@"%";')
print('   FLUSH PRIVILEGES;')
print('   EXIT;')
print()

print('🎯 COMANDOS COMPLETOS PARA EXECUTAR:')
print('=' * 50)
print('# 1. Instalar MariaDB')
print('sudo yum install mariadb-server -y')
print()
print('# 2. Iniciar MariaDB')
print('sudo systemctl start mariadb')
print('sudo systemctl enable mariadb')
print()
print('# 3. Configurar MariaDB')
print('sudo mysql_secure_installation')
print()
print('# 4. Criar banco de dados')
print('sudo mysql -u root -p')
print('# Executar comandos SQL acima')
print()
print('# 5. Verificar status')
print('sudo systemctl status mariadb')
print()
print('# 6. Reiniciar aplicação')
print('sudo systemctl restart flask-app')
print()

print('🔍 VERIFICAR INSTALAÇÃO:')
print('=' * 40)
print('📋 Verificar se MariaDB está instalado:')
print('   mysql --version')
print()
print('📋 Verificar status do serviço:')
print('   sudo systemctl status mariadb')
print()
print('📋 Verificar se está rodando:')
print('   sudo systemctl is-active mariadb')
print()
print('📋 Verificar se está habilitado:')
print('   sudo systemctl is-enabled mariadb')
print()

print('🚨 ALTERNATIVA: USAR SQLITE')
print('=' * 50)
print('💡 DICA: Se MariaDB não funcionar, use SQLite:')
print()
print('1. 📦 SQLite já vem instalado')
print('2. 🔧 Modificar database.py para usar SQLite')
print('3. 🗄️ Criar banco local')
print('4. ✅ Funciona sem configuração adicional')
print()

print('🎯 RESUMO:')
print('=' * 30)
print('✅ Problema: MySQL não disponível no Amazon Linux 2023')
print('✅ Solução 1: Usar MariaDB (compatível com MySQL)')
print('✅ Solução 2: Usar SQLite (mais simples)')
print('✅ Recomendação: Tentar MariaDB primeiro')
print()

print('🚀 PRÓXIMOS PASSOS:')
print('=' * 30)
print('1. 🔧 Instalar MariaDB')
print('2. 🗄️ Configurar banco de dados')
print('3. 🚀 Reiniciar aplicação')
print('4. ✅ Verificar status')
print('5. 🌐 Testar aplicação')
print()

print('🎉 APÓS CORRIGIR:')
print('=' * 30)
print('✅ MariaDB: active (running)')
print('✅ Flask-app: active (running)')
print('✅ Nginx: active (running)')
print('✅ Aplicação: http://SEU_IP_PUBLICO')
print()

print('🚀 SUA APLICAÇÃO ESTARÁ FUNCIONANDO!')
print('MariaDB é compatível com MySQL e funciona perfeitamente!')
