#!/usr/bin/env python3
"""
Script para automatizar comandos AWS para iniciantes
"""

print('🚀 COMANDOS AUTOMÁTICOS PARA AWS - INICIANTES')
print('=' * 60)

print('📋 COMANDOS PARA EXECUTAR NA EC2:')
print()

print('1. 🔄 ATUALIZAR SISTEMA:')
print('   sudo yum update -y')
print()

print('2. 🗄️ INSTALAR MYSQL:')
print('   sudo yum install mysql-server -y')
print('   sudo systemctl start mysqld')
print('   sudo systemctl enable mysqld')
print('   sudo mysql_secure_installation')
print()

print('3. 🐍 INSTALAR PYTHON:')
print('   sudo yum install python3.11 python3.11-pip -y')
print('   sudo yum install git -y')
print()

print('4. 📁 CRIAR DIRETÓRIO:')
print('   mkdir -p /home/ec2-user/mercadolivre-app')
print('   cd /home/ec2-user/mercadolivre-app')
print()

print('5. 📦 INSTALAR DEPENDÊNCIAS:')
print('   pip3.11 install -r requirements_aws.txt')
print()

print('6. 🌐 INSTALAR NGINX:')
print('   sudo yum install nginx -y')
print()

print('7. 🔧 CONFIGURAR NGINX:')
print('   sudo nano /etc/nginx/conf.d/flask.conf')
print('   # Cole o conteúdo do arquivo de configuração')
print()

print('8. 🚀 INICIAR NGINX:')
print('   sudo systemctl start nginx')
print('   sudo systemctl enable nginx')
print()

print('9. 🔧 CONFIGURAR SERVIÇO:')
print('   sudo nano /etc/systemd/system/flask-app.service')
print('   # Cole o conteúdo do arquivo de serviço')
print()

print('10. 🚀 INICIAR SERVIÇO:')
print('    sudo systemctl daemon-reload')
print('    sudo systemctl start flask-app')
print('    sudo systemctl enable flask-app')
print()

print('11. 🔥 CONFIGURAR FIREWALL:')
print('    sudo firewall-cmd --permanent --add-port=80/tcp')
print('    sudo firewall-cmd --permanent --add-port=443/tcp')
print('    sudo firewall-cmd --reload')
print()

print('12. ✅ VERIFICAR STATUS:')
print('    sudo systemctl status nginx')
print('    sudo systemctl status flask-app')
print('    sudo systemctl status mysqld')
print()

print('13. 📋 VERIFICAR LOGS:')
print('    sudo journalctl -u flask-app -f')
print()

print('14. 🌐 TESTAR APLICAÇÃO:')
print('    # Acesse no navegador: http://SEU_IP_PUBLICO')
print()

print('📝 CONFIGURAÇÕES NECESSÁRIAS:')
print()

print('🔧 ARQUIVO: /etc/nginx/conf.d/flask.conf')
print('server {')
print('    listen 80;')
print('    server_name _;')
print('    ')
print('    location / {')
print('        proxy_pass http://127.0.0.1:5000;')
print('        proxy_set_header Host $host;')
print('        proxy_set_header X-Real-IP $remote_addr;')
print('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;')
print('        proxy_set_header X-Forwarded-Proto $scheme;')
print('    }')
print('}')
print()

print('🔧 ARQUIVO: /etc/systemd/system/flask-app.service')
print('[Unit]')
print('Description=Flask App')
print('After=network.target')
print('')
print('[Service]')
print('User=ec2-user')
print('WorkingDirectory=/home/ec2-user/mercadolivre-app')
print('Environment=PATH=/usr/bin/python3.11')
print('ExecStart=/usr/bin/python3.11 app.py')
print('Restart=always')
print('')
print('[Install]')
print('WantedBy=multi-user.target')
print()

print('🗄️ CONFIGURAÇÃO MYSQL:')
print('sudo mysql -u root -p')
print('# No MySQL:')
print('CREATE DATABASE sistema_ml;')
print('CREATE USER "admin"@"%" IDENTIFIED BY "2154";')
print('GRANT ALL PRIVILEGES ON sistema_ml.* TO "admin"@"%";')
print('FLUSH PRIVILEGES;')
print('EXIT;')
print()

print('🚨 SOLUÇÃO DE PROBLEMAS:')
print()

print('❌ Se a aplicação não carregar:')
print('   sudo journalctl -u flask-app -f')
print('   ps aux | grep python')
print('   netstat -tlnp | grep 5000')
print('   sudo systemctl restart flask-app')
print()

print('❌ Se MySQL não conectar:')
print('   sudo systemctl status mysqld')
print('   mysql -u root -p -e "SHOW DATABASES;"')
print('   sudo systemctl restart mysqld')
print()

print('❌ Se não conseguir conectar SSH:')
print('   1. Verificar Security Group (porta 22)')
print('   2. Verificar permissões do arquivo .pem')
print('   3. Tentar conectar de outro IP')
print()

print('🎯 RESUMO DOS PASSOS:')
print('   1. Criar conta AWS')
print('   2. Criar instância EC2')
print('   3. Conectar via SSH')
print('   4. Instalar MySQL')
print('   5. Instalar Python')
print('   6. Upload dos arquivos')
print('   7. Instalar dependências')
print('   8. Configurar Nginx')
print('   9. Configurar serviço')
print('   10. Iniciar serviços')
print('   11. Configurar firewall')
print('   12. Testar aplicação')
print()

print('⏱️ TEMPO TOTAL: 45-60 minutos')
print('🎉 RESULTADO: Aplicação online na AWS!')
