#!/usr/bin/env python3
"""
Script para verificar IPs do EC2
"""

print('🔍 VERIFICANDO IPs DO EC2')
print('=' * 40)

print('📋 COMANDOS PARA EXECUTAR NO EC2:')
print('=' * 40)
print()
print('1. 🌐 IP Público:')
print('   curl -s http://169.254.169.254/latest/meta-data/public-ipv4')
print()
print('2. 🏠 IP Privado:')
print('   curl -s http://169.254.169.254/latest/meta-data/local-ipv4')
print()
print('3. 🔍 IP da Subnet:')
print('   curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/*/subnet-ipv4-cidr-block')
print()

print('🎯 CONFIGURAÇÃO DO SECURITY GROUP:')
print('=' * 50)
print('📋 REGRA RECOMENDADA:')
print('   Type: MySQL/Aurora')
print('   Protocol: TCP')
print('   Port: 3306')
print('   Source: [IP_PRIVADO_DO_EC2]/32')
print()
print('💡 EXEMPLO:')
print('   Se o IP privado for 172.31.4.248')
print('   Use: 172.31.4.248/32')
print()

print('🔧 PASSOS NO AWS CONSOLE:')
print('=' * 40)
print('1. 🌐 Acessar: https://console.aws.amazon.com')
print('2. 🔍 Navegar: Services → RDS → Databases')
print('3. 📋 Selecionar: mercadolivre-db')
print('4. 🔒 Ir para: Connectivity & security → VPC security groups')
print('5. ⚙️ Editar: Actions → Edit inbound rules')
print('6. ➕ Adicionar regra com os dados acima')
print('7. 💾 Salvar: Save rules')
print()

print('⏱️ TEMPO DE PROPAGAÇÃO:')
print('=' * 30)
print('⏰ Security Group: 1-2 minutos')
print('⏰ Total: 2-3 minutos')
print()

print('🧪 APÓS CONFIGURAR:')
print('=' * 30)
print('1. ⏳ Aguardar 2-3 minutos')
print('2. 🧪 Testar conexão:')
print('   python3.11 test_rds_connection.py')
print('3. 🗄️ Criar banco:')
print('   python3.11 create_database.py')
print()

print('🚨 IMPORTANTE:')
print('=' * 20)
print('✅ Use o IP PRIVADO do EC2')
print('✅ Formato: IP/32')
print('✅ Exemplo: 172.31.4.248/32')
print('✅ Aguarde 2-3 minutos após configurar')
print()

print('🚀 EXECUTE OS COMANDOS NO EC2 E CONFIGURE O SECURITY GROUP!')
